### ISSUE TITLE
GradualRolloutUserId doesn't work.

### ISSUE THREAD

**Issue by tckb** [Unleash/unleash-client-java#101]
Hi, I am trying to test Unleash feature toggles. I use Gitlab UI to toggle the features and, it looks like the `GradualRolloutUserId` doesn't seem to be working. At least, I am unable to make it to work. 

I have the following feature flags defined:

<img width="1448" alt="image" src="https://user-images.githubusercontent.com/939542/76294161-a169fd00-62b2-11ea-99ed-469b10fcc981.png">
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/939542/76294203-b5adfa00-62b2-11ea-8df7-a352d645a93c.png">

`flag1` works as far as enabling for `test@test.com` but the percentage rollout doesn't work. 

I have a following sample client code. 
```java 
// config

  public Unleash unleash(UnleashConfig config) {
    return new DefaultUnleash(config);
  }

  public UnleashConfig unleashConfig() {
    return UnleashConfig.builder()
        .appName(appName)
        .instanceId(unleashInstanceId)
        .unleashAPI(unleashApiUrl)
        .fetchTogglesInterval(10)
        .synchronousFetchOnInitialisation(true)
        .build();
  }

// client
 @RequestMapping("/")
  public String index(@RequestParam String id) {
    String message = "Greetings from Spring Boot!";
    UnleashContext ctx = UnleashContext.builder().environment(appName).userId(id).build();

    if (unleash.isEnabled("flag1", ctx)) {
      message += " flag1 is turned on";
    }

    if (unleash.isEnabled("flag2", ctx)) {
      message += " flag2 is turned on";
    }

    return message;
  }
```

The response to `http://localhost:8080?id=test@test.com` is always `Greetings from Spring Boot! flag1 is turned on`

here's the repo

```json
{   "features":[      {         "name":"flag2",
         "enabled":false,
         "strategies":[            {               "name":"gradualRolloutUserId",
               "parameters":{
                  "groupId":"default",
                  "percentage":"90"
               
}
            
},
            {               "name":"userWithId",
               "parameters":{
                  "userIds":"test"
               
}
            
}
         
]
      
},
      {         "name":"flag1",
         "enabled":true,
         "strategies":[            {               "name":"gradualRolloutUserId",
               "parameters":{
                  "groupId":"default",
                  "percentage":"50"
               
}
            
},
            {               "name":"userWithId",
               "parameters":{
                  "userIds":"test@test.com"
               
}
            
}
         
]
      
}
   
],
   "version":1
}
```

Am I missing something here ?

**Comment by ivarconr** [comment]
it will be sticky for the same userId. Have you tried changing the userId?

**Comment by tckb** [comment]
@ivanklee86  yes this is what I was expecting. changing the user id works, i.e., feature is disabled for different user id. But, I expect that the user id "test@test.com" has the feature enabled for 50% of time

**Comment by ivarconr** [comment]
Then you need to use the GradualRolloutRandom strategy, which is random per isEnabled call. The reason GradualRolloutUserId is sticky is to provide a consistent experience for users. Having a feature flicker on/off can be sub- optimal for a user of your solution (reloading the page removes the feature).

Read more on built-in strategies here:
https://unleash.github.io/docs/activation_strategy

**Comment by tckb** [comment]
@ivarconr  it looks like this strategy is not provided by the server. I read the guide and am a bit puzzled to understand the "GradualRollout" with userId stickyness: what does percentage indicate ?  -- my understanding is that the rollout percentage is applicable to only that user, for example. 
```json

{
   "features":[
      {
         "name":"flag1",
         "enabled":true,
         "strategies":[
            {
               "name":"gradualRolloutUserId",
               "parameters":{
                  "groupId":"default",
                  "percentage":"50"
               }
            },
            {
               "name":"userWithId",
               "parameters":{
                  "userIds":"test@test.com"
               }
            }
         ]
      }
   ],
   "version":1
}
```

I would like to know what the above  mean..

**Comment by ivarconr** [comment]
So the example you show there uses two strategies. If either one of them matches the toggle will be considered enabled. 

- `userWithId` - Allow you to define a list of users that will always have the toggle enabled. 
- `gradualRolloutUserId` - Allows you to gradual roll-out to a set of your identified users, according the the percentage. 

Please be advised that multiple strategies are OR-ed together. If you need ANDing as well you might consider [Unleash-hosted](https://www.unleash-hosted.com), which supports that via strategy constraints.

**Comment by tckb** [comment]
@ivarconr thanks for the explanation. I think I got the OR thing from testing. My problem is `gradualRolloutUserId` isn't working with the percentage. If the percentage is 50%, then it would mean that the feature is available 50% of time. correct?

**Comment by ivarconr** [comment]
>  If the percentage is 50%, then it would mean that the feature is available 50% of time. correct?

Across a set of different userIds it will be 50% yes. For the same userId it will either be either true or false.

**Comment by tckb** [comment]
> > If the percentage is 50%, then it would mean that the feature is available 50% of time. correct?
> 
> Across a set of different userIds it will be 50% yes. For the same userId it will either be either true or false.

Ah! that's the catch! sorry this is why I was confused. I assumed it's for the same user. Makes sense for across the set of users. Not the remaining question is -- how does the percent distribution works?

**Comment by tckb** [comment]
thanks for the support @ivarconr  I am closing this issue. If there's anything you would like to add, please do comment.
