### ISSUE TITLE
The `Unleash` interface should have a `close()` method to stop the executor

### ISSUE THREAD

**Issue by Enrico2** [Unleash/unleash-client-java#102]
In order to properly shutdown a server that's running an Unleash client, all scheduled threads should be shutdown gracefully.

With the current implementation there is no clean way to shutdown the `UnleashScheduledExecutor`. If we're using the default implementation of `UnleashScheduledExecutorImpl`, all fields that would allow us to do so are either private, or are swallowed; The `ScheduledFuture` object returned from `setInterval` is not set to any field in the 2 constructors that call it, `UnleashMetricServiceImpl` and `FeatureToggleRepository`. Nor is the `ScheduledThreadPoolExecutor` exposed (it has a `shutdown()` method).

Our only option right now is to implement our own `UnleashScheduledExecutor`, pass it in as the config, and have a `close()` or `shutdown()` method on it. (we can't even use `UnleashScheduledExecutorImpl` because of the private fields.

My proposal would be that that interface add a `close()` method (or implement `Closeable`) and that the `Unleash` interface would do the same.
the implementation of the latter would get the executor from the `config` instance and call `close()` on it. That way, no matter which implementation of `UnleashScheduledExecutor` one would use, they can shut it down via the main interface.

This would be a breaking change, since it'd change interfaces that might already be implemented by users.

**Comment by ivarconr** [comment]
This is a great suggestion and I it wold be awesome if you could work on this, I will support you on this. By adding close with a default implementation in the interface would allow us to introduce it without making it a breaking change.

**Comment by Enrico2** [comment]
Cool cool, will work on this. It's been a while since I wrote Java (doing mostly Kotlin these days), does it support implementations in an _interface_? Does it not have to be an abstract class?

**Comment by ivarconr** [comment]
Java interfaces supports default implementations these days. We already take advantage of this in the `Unleash` interface:
https://github.com/Unleash/unleash-client-java/blob/master/src/main/java/no/finn/unleash/Unleash.java#L11-L13

**Comment by Enrico2** [comment]
ah, nice!

**Comment by Enrico2** [comment]
https://github.com/Unleash/unleash-client-java/pull/103

**Comment by ivarconr** [comment]
released as 3.3.1
