### ISSUE TITLE
Improve client authentication alternatives

### ISSUE THREAD

**Issue by goober** [Unleash/unleash-client-java#105]
The current support for client authentication in the java client is to use a shared secret as described in https://unleash.github.io/docs/securing_unleash#securing-the-client-api

However, I have configured the client api to validate a jwt with a given scope for accessing the client api to conform with the workflow we use for all our services. What I can read from the source code this is not currently supported since you can only configure fixed headers for your requests. The JWT needs to be renewed when it has expired so my question is if you have any suggestions how it could be resolved with the current implementation of unleash-client-java or if support for more dynamic authentication is something that you think would fit in the the client library?

**Comment by ivarconr** [comment]
We will soon (within the next 24hrs) release next version of the java-client where you can change the headers dynamically. See https://github.com/Unleash/unleash-client-java/pull/104 for reference.

**Comment by goober** [comment]
Great minds think alike :) Great news! Thanks you for the fast feedback
