### ISSUE TITLE
Everytime this returns fixed variant

### ISSUE THREAD

**Issue by lchrennew** [Unleash/unleash-client-java#110]
https://github.com/Unleash/unleash-client-java/blob/e4c12f438e5f0fe2dcd9a64c604a8dc5b4dbe0d1/src/main/java/no/finn/unleash/variant/VariantUtil.java#L68

**Comment by ivarconr** [comment]
Hi, could you please provide a bit more context? What are the input, and what do yet get as the return value you get?

**Comment by ivarconr** [comment]
Closing because of lack of details
