### ISSUE TITLE
Kotlin support for Java client

### ISSUE THREAD

**Issue by alxsimo** [Unleash/unleash-client-java#114]
How about adding Kotlin support for the Java client?

I already saw there is a Kotlin migrated client, it's just migrated, no extra features added.
The power of Kotlin comes from extension functions, and we could have inside this project, a separated source set for Kotlin extensions and maybe even migrate some code.

**Comment by ivarconr** [comment]
This is an interesting idea. Kotlin has a few interesting capabilities that could improve create even better and more advanced API surfaces for the users. 

I think it still is good to be able to ship pure java SDK without Kotlin specific dependencies.

**Comment by chriswk** [comment]
To make it better to use the java client from kotlin, we could consider adding @Nullable and @NotNullable annotations to our method parameters, allowing Kotlin users to make the compiler do null-checks for them.

**Comment by ivarconr** [comment]
Would it make sense to have a separate Kotlin SDK repo? I assume that we would quite different API surface. We could possible share some of the basic building blocks, such as the strategy implementation.

**Comment by checketts** [comment]
No, there is no need to create a separate repo. Any Kotlin specific pieces can co-exist without causing trouble for the Java users. I've created similar Kotlin extensions for other projects and would consider submitting a PR if this sounds reasonable. The key is marking the kotlin sdk as an 'optional' Maven dependency (Since Kotlin projects will already have it).

I would do a first pass adding the `@Nullable` annotations then do a subsequent PR that adds a Kotlin DSL.

**Comment by checketts** [comment]
Current Kotlin DSL that I've been playing with:

##Make the UnleashConfig builder use a receiver block so you can call builder methods in that block and make the required parameters part of the base call (named parameter work there as well)
```
 val config = unleashConfig("bob","http://localhost:4242/api/" ) {
            unleashContextProvider(contextProvider)
        }
```        

Feature enabled check options:
```
//Normal 'if' block, no changes
        if(unleash.isEnabled("test")) {
            print("yes")
        } else {
            print("no")
        }

//Create an extra 'infix' notation, I don't love it, but if there is a good infix notation that could make feature checks stand out more I think this could be good
        if(unleash feature "test") {
            print("yes")
        } else {
            print("no")
        }

//When notation also doesn't require any DSL changes. I don't find it much more succinct than the simple 'if'
        when(unleash.isEnabled("test")) {
            true -> print("yes")
            else -> print("no")
        }
```

**Comment by checketts** [comment]
Here is on Kotlin-ism that I've begun using.

Given the extension function:

```kotlin
operator fun Unleash.invoke(toggleName: String) = this.isEnabled(toggleName)
```

I name my Unleash variable `featureFlag` and now my toggle checks are bit cleaner:

```kotlin
if(featureFlag("myFeature")) {
  useFeature()
} else {
  useOldWay()
}
```

**Comment by chriswk** [comment]
>  I really like it when using expressions:
> val result = if(featureFlag("calculateNewWay")) calcNewWay() else calcOldWay()
That one looked really good. :)
