### ISSUE TITLE
Support for precalcuating toggles and manual metrics

### ISSUE THREAD

**Issue by checketts** [Unleash/unleash-client-java#124]
I have a number of SPA (Single Page Applications) that will run in a user's browser. The code in the browser is written in Typescript (Angular or React)

I would like to add 2 capabilities: 

# Precalculated toggles
A way to pre-calculate all toggles for a given UnleashContext without triggering the corresponding metrics

This will let me generate the results of toggles to send to the browser which can then be used by the client side code.

# Manually sending metrics

Periodically when the front-end checks back for toggle updates it can report its metrics to the backend which will be able to forward them on to Unlease.

I don't want my frontend code calling Unleash directly due to differing authentication needs and scalability.

Would this capability be welcome as a PR?

**Comment by ivarconr** [comment]
Hi @checketts,

As part of the commercial offering, we already have the [unleash-proxy](https://www.unleash-hosted.com/articles/the-unleash-proxy), providing this functionalities (and more) on top of the [Node SDK](https://github.com/Unleash/unleash-client-node). 

Our plan is to also open-source the Unleash Proxy for everyone, but that would take a few more sprints before we are able to prioritize this work (it will require us to do some cleanup to make it 100% compatible with the community version of Unleash). You might want to use the Unleash Proxy as the official way to integrate with SPAs

That being said, I do not see any harm of adding these capabilities for the Java SDK as well.

**Comment by checketts** [comment]
Thanks for the tip about unleash-proxy! I'll keep an eye out for when it becomes open source. 

I've made a minimal PR to the Java client that I believe will allow me to move forward for now.

**Comment by checketts** [comment]
Closing since this is addressed in version 4.1.0
