### ISSUE TITLE
feat: Support warm-up state from "location"

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-java#129]
I some scenarios one could risk that the unleash-api is unavailable on startup (networks are unreliable after all). And relying on the built in backup file could not be an option in the world of immutable (docker) containers. 

It could be good to allow the user to specify the initial state to use (instead of the built-in backup-file location) where the user have curated the latest feature toggle configuration snapshot to use. This should be a pure dump from the `/api/client/features` endpoint. The dump could be produced at the CI server when the application is bundled or later through the infrastructure (e.g. config maps or similar). 

We would (probably?) not want to read the temporary backup if such "hot backup location" is defined. The location could either be a absolute file (in the docker container) or a URL (e.g. a static file server, S3 or simial).

**Comment by checketts** [comment]
If a warm-up state exists, then it seems like the temporary backup would still be preferred (if it has content) since it would have been created after the warm-up state. Am I misunderstanding a part of that?

**Comment by ivarconr** [comment]
I think it depends. Say the warm-up location is a file on S3 which is updated regularly (or as a result of the webhook), then it would probably be as fresh as it gets? 

But yes, I don't feel there is a clear answer, but given the temp backup file exists and the application has been running recently, it is probably the freshest state in most situations.
