### ISSUE TITLE
feat: Adding custom proxy exclusively for unleash

### ISSUE THREAD

**Issue by hcf** [Unleash/unleash-client-java#136]
We need to have the possibility of explicitly setting the proxy only for the http connection used by unleash, without setting a global proxy. We could use the global proxy, but when doing so would need to set `-Dhttp.nonProxyHosts="all|the|other|domains|we|are|currently|calling|but|not|unleash-hosted"`, which seems counterintuitive.

**Comment by ivarconr** [comment]
See #137
