### ISSUE TITLE
Move package to io.getunleash

### ISSUE THREAD

**Issue by chriswk** [Unleash/unleash-client-java#138]
We should move the library away from the no.finn umbrella now that we've acquired the io.getunleash groupId.

**Comment by checketts** [comment]
This kind of a change is very disruptive for users. For the most used classes (and interfaces), I recommend duplicating the class, and having the old class sub-class the new class. The allows a transition.

Example:

`no.finn.unleash.Unleash extends io.getunlesh.unleash.Unleash`
