### ISSUE TITLE
Client SDK API Token

### ISSUE THREAD

**Issue by ptlamgithub** [Unleash/unleash-client-java#143]
Unleash server: 4.1.4
Java Client SDK: 4.1.0

The document states that starting v4.0.0, clients are required to provide an API token to access an Unleash instance. It doesn't appear so as I am able to access the Unleash server and fetch the feature toggles using the Java SDK without providing the API token.

**Comment by checketts** [comment]
So is your question, 'How do I provide a token?' Or is it instead that you want a way to fetch features without a token?

**Comment by ivarconr** [comment]
What is the authentication type (auth_type) you are currently using? I just started a fresh v4.1.4 unleash server instance, and it does require me to provide a api token:

```sh
➜  ~ http http://localhost:4242/api/client/features                            
HTTP/1.1 401 Unauthorized
```

**Comment by ptlamgithub** [comment]
I am using keycloak auth as follows:

      unleash.start({
        authentication: {
          type: 'custom',
          customAuthHandler: enableKeycloakOauth,
         },
      });

**Comment by ivarconr** [comment]
With a custom auth handle it is up to your code to perform validation on the access. 

If you have followed the example ([link](https://github.com/Unleash/unleash-examples/tree/main/v4/securing-keycloak-auth)) you will probably add a requirement that there needs to exists a user on the request (the apiTokenMiddleware) if someone access `/api`.

This is how the OSS auth code solves that:
https://github.com/Unleash/unleash/blob/master/src/lib/middleware/oss-authentication.ts

**Comment by ptlamgithub** [comment]
Ok I see. By using the custom auth handler, it overrides the default auth handler which requires the API token on accessing the /api/client endpoints. I added access control on /api/client in my custom auth handler and it worked as expected. Thanks!
