### ISSUE TITLE
Add documentation for additional configuration parameters

### ISSUE THREAD

**Issue by jpranin-fabric** [Unleash/unleash-client-java#153]
I'd like to request more documentation on what customizable methods are available when configuring Unleash. For example, I didn't realize we had an option to change how often we are polling Unleash for updates until @ivarconr pointed out the `fetchTogglesInterval` configuration to me in https://github.com/Unleash/unleash-client-java/blob/main/src/main/java/io/getunleash/util/UnleashConfig.java#L376

**Comment by thomasheartman** [comment]
Hi, @jpranin-fabric! Yeah, for sure; this is a great idea. Thanks for raising it. Let me see what I can do! 🙋🏼

**Comment by thomasheartman** [comment]
Any time ☺️ And thanks for reporting it and helping us improve 🙏
