### ISSUE TITLE
Add getFeatureToggleDefinition to Unleash interface

### ISSUE THREAD

**Issue by Chaosmi** [Unleash/unleash-client-java#161]
### Describe the feature request

Would it be possible to add `getFeatureToggleDefinition` to Unleash interface so we don't have to refer to concrete `DefaultUnleash`?

### Background

This will mean we can refer to the interface only and avoid casting to `DefaultUnleash`

### Solution suggestions

Raised PR https://github.com/Unleash/unleash-client-java/pull/160

**Comment by andreas-unleash** [comment]
Hey, thank you for reaching out and your PR.  I left a comment about where this functionality could sit
