### ISSUE TITLE
Unleash Codegen Gradle Plugin

### ISSUE THREAD

**Issue by yahorbarkouski** [Unleash/unleash-client-java#178]
### Describe the feature request

I've prepared a small but useful gradle plugin for autogenerating unleash features (so far only for kotlin), would be very interesting to hear your opinion, thanks a lot in advance :) https://github.com/yahorbarkouski/unleash-codegen-gradle-plugin

**Comment by FredrikOseberg** [comment]
@yahorbarkouski Cool! @chriswk and @andreas-unleash want to take a look?

**Comment by andreas-unleash** [comment]
I like what you've done @yahorbarkouski.  I can see it being very useful for developers. Great job !

**Comment by sighphyre** [comment]
Hey @yahorbarkouski, this looks very cool, would you be okay if we added a link to this in the README in this project?

**Comment by yahorbarkouski** [comment]
hey guys, thanks a lot for your kind words! I hope this will actually be useful to the community

**Comment by yahorbarkouski** [comment]
> Hey @yahorbarkouski, this looks very cool, would you be okay if we added a link to this in the README in this project?

gladly!

**Comment by ybarkouski** [comment]
hey guys, we've just transferred my repo to superside's org open source organization, which will allow our organization to support the project without me too :) new repo url: https://github.com/superside-oss/unleash-codegen-gradle-plugin

**Comment by chriswk** [comment]
Thanks for this. We'll look into adding a link in the Unleash documentation, but this is not an actionable item for this repo.
