### ISSUE TITLE
DefaultUnleash.isEnabled(toggleName, context) silently dropping context

### ISSUE THREAD

**Issue by hnicke** [Unleash/unleash-client-java#181]
### Describe the bug

The `Unleash` Interface provides a function `isEnabled(toggleName,  context)` with a default implementation.
In the default implementation, the context is silently dropped.
This is expected behavior i guess.

However, he `DefaultUnleash` implementation is missing an override for this function.
This leads to the behavior where `DefaultUnleash.isEnabled(toggleName, context)` silenlty drops the context.
Note that `DefaultUnleash.isEnabled(toggleName, context, defaultValue)` does not drop the context.

### SDK information (language and version)

java client sdk 7.0.0

**Comment by pransh15** [comment]
Hey @hnicke 👋 
Thanks for submitting this, someone from the team will get back to you on this soon. 😄

**Comment by gastonfournier** [comment]
Hi @hnicke the `DefaultUnleash` implementation seems to be working as expected (check #184 where I explained why is that). The interface is confusing nevertheless, so I'll bring this to @chriswk as an enhancement.

**Comment by hnicke** [comment]
Thank you for looking into this.
My bad - you are right!
For some odd reason it didn't work for me last week.
I can confirm it is working as intended.
Sorry for the inconvenience.

**Comment by gastonfournier** [comment]
No problem, still it is something that might be worth looking at!
