### ISSUE TITLE
Impression data flag as part of getFeatureToggleDefinition

### ISSUE THREAD

**Issue by sebastian-bury** [Unleash/unleash-client-java#200]
### Describe the feature request

I would like the moreOperations (src/main/java/io/getunleash/MoreOperations.java) method getFeatureToggleDefinition to provide the flag on if impression data is enabled or disabled for that toggle. This comes as part of the payload from /api/client/features but is discarded by the Java SDK instead of stored.

**Comment by sighphyre** [comment]
Closed by #201
