### ISSUE TITLE
CHANGELOG.md file is severely outdated

### ISSUE THREAD

**Issue by gusevalexey0** [Unleash/unleash-client-java#250]
### Describe the bug

Hello! 

I was trying to find any info about compatibility between different versions of this SDK and different version of Unleash server. Unfortunately, there is no such info available. The I've tried to find some implicit hints about backward compatibility through history of changes. It turned out that latest notes in `CHANGELOG.md` are connected with a release 6.0.1. As of now release 9.2.4 is available. Was the data about changes after 6.0.1 tracked anyhow except git commits? Is it possible to restore it?

### Expected behavior

`CHANGELOG.md` is up-to-date

### Subscription type

None

### Hosting type

None

**Comment by ivarconr** [comment]
Hi, 

we moved away from the changelog and into release notes directly on github. We should have updated the changelog to inform about that, sorry! 

https://github.com/Unleash/unleash-client-java/releases
