### ISSUE TITLE
client metrics

### ISSUE THREAD

**Issue by sveinelo** [Unleash/unleash-client-java#3]
copied from https://github.com/finn-no/unleash/issues/21

jarib:
There's currently no way of tracking what toggles are being used across applications. The simplest I can think of is to add easy statsd/graphite reporting in the client. 

Perhaps look at [Yammer Metrics](https://dropwizard.github.io/metrics/3.1.0/). From reading the Kafka docs it sounds pretty nice:

> Kafka uses Yammer Metrics for metrics reporting in both the server and the client. This can be configured to report stats using pluggable stats reporters to hook up to your monitoring system.

hennings:
Codahale Metrics (successor to Yammer metrics) is a nice library for timing
histograms, counters and gauges. There are several publishers you can plug
in to send the data to graphite, a servlet etc.

Henning
On 21 Oct 2014 15:33, "Jari Bakken" notifications@github.com wrote:

> There's currently no way of tracking what toggles are being used across
> applications. The simplest I can think of is to add easy statsd/graphite
> reporting to the client.
> 
> Perhaps look at Yammer Metrics
> https://dropwizard.github.io/metrics/3.1.0/. From reading the Kafka
> docs it sounds pretty nice:
> 
> Kafka uses Yammer Metrics for metrics reporting in both the server and the
> client. This can be configured to report stats using pluggable stats
> reporters to hook up to your monitoring system.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/finn-no/unleash/issues/21.

**Comment by ivarconr** [comment]
This is mostly done on the metrics branch. Only one thing left: 

- [ ] add option to disable metrics (relevant for clients running agains older unleash server).

**Comment by ivarconr** [comment]
see #30
