### ISSUE TITLE
Unable to detect failures in HttpToggleFetcher

### ISSUE THREAD

**Issue by jan-berge-ommedal** [Unleash/unleash-client-java#49]
The current API of Unleash/HttpToggleFetcher makes it difficult to detect if HttpToggleFetcher is actually able to fetch toggles or if it experiences for example network failures, authentication/authorization failures or simply 404s because because somebody shut down or moved the unleash server.

It would be nice if applications are able to observe such problems through the API.

**Comment by ivarconr** [comment]
released as 3.1.0
