### ISSUE TITLE
Synchronous call to pull toggles when instantiating the unleash client

### ISSUE THREAD

**Issue by ryanm35** [Unleash/unleash-client-java#57]
Right now it looks like when the unleash client is instantiated a background thread is setup to query the toggles from the server. I am running into an issue where a call to `getFeatureToggleNames()` is returning an empty list because the call is made too soon after the instantiation of the client and no backup file existed. 

Can the instantiation make an synchronous call to update first and then setup the background thread?

**Comment by ivarconr** [comment]
Released as part of `unleash-client-java:3.1.1`
