### ISSUE TITLE
Figure out how to also build with jdk11

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-java#60]
Travis has jdk support for openjdk11. Also need to touch the pom-file to specify jdk11. 

Wanted outcome:
Travis build with jdk8 and jdk11.

**Comment by joschi** [comment]
> Also need to touch the pom-file to specify jdk11.

Why exactly would we need to modify the POM file? As far as I understand, the baseline for the Unleash client should still be Java 8, shouldn't it?
