### ISSUE TITLE
Local backup json file is not getting updated

### ISSUE THREAD

**Issue by vkatoch2000** [Unleash/unleash-client-java#71]
Local backup json file is not getting updated when disabled labels in UI, disable /enable the lables in admin GUI , is not reflected in unleash client in multiple AWS ec2 instance, it only picks up the first time settings

**Comment by vkatoch2000** [comment]
Local backup json file is not getting updated when disabled labels in UI

**Comment by ivarconr** [comment]
Hi, we just released a new Subscriber API, which will make it much easier to debug this. 

Would you mind upgrading your unleash-client-java to version **3.2.2**?

With the new version you can register a custom UnleashSubscriber to log out what the unleash-client is actually doing internally:

```java
UnleashConfig unleashConfig = new UnleashConfig.Builder()
	.appName("java-test")
	.instanceId("instance y")
	.unleashAPI("https://unleash.herokuapp.com/api/")
	.subscriber(new UnleashSubscriber() {
	    @Override
	    public void onReady(UnleashReady ready) {
		System.out.println("Unleash is ready");
	    }

	    @Override
	    public void togglesFetched(FeatureToggleResponse toggleResponse) {
		System.out.println("Fetch toggles with status: " + toggleResponse.getStatus());
	    }

	    @Override
	    public void togglesBackedUp(ToggleCollection toggleCollection) {
		System.out.println("Backup stored.");
	    }

	    @Override
	    public void toggleBackupRestored(ToggleCollection toggleCollection) {
		System.out.println("Backup read.");
	    }

	})
	.build();

Unleash unleash = new DefaultUnleash(unleashConfig);
```

When the client behaves as expected you should get something like this:

```
Backup read.
Fetch toggles with status: CHANGED
Backup stored.
Unleash is ready
Fetch toggles with status: NOT_CHANGED
Fetch toggles with status: NOT_CHANGED
....
```

And when a toggle is changing status in the UI / server you should see:

```
....
Fetch toggles with status: NOT_CHANGED
Fetch toggles with status: CHANGED
Backup stored.
Fetch toggles with status: NOT_CHANGED
....
```

**Comment by vkatoch2000** [comment]
2019-02-26 10:21:59.202  INFO 1652 --- [sh-api-executor] c.w.submgn.config.WebConfigurer          : Backup read.
10:21:59.202 [INFO ] [no_tenant ] c.w.s.config.WebConfigurer     - Backup read.
2019-02-26 10:21:59.895  INFO 1652 --- [sh-api-executor] c.w.submgn.config.WebConfigurer          : Fetch toggles with status: CHANGED
10:21:59.895 [INFO ] [no_tenant ] c.w.s.config.WebConfigurer     - Fetch toggles with status: CHANGED
2019-02-26 10:21:59.900  INFO 1652 --- [sh-api-executor] c.w.submgn.config.WebConfigurer          : Backup stored.
10:21:59.900 [INFO ] [no_tenant ] c.w.s.config.WebConfigurer     - Backup stored.
2019-02-26 10:21:59.904  INFO 1652 --- [sh-api-executor] c.w.submgn.config.WebConfigurer          : Unleash is ready
10:21:59.904 [INFO ] [no_tenant ] c.w.s.config.WebConfigurer     - Unleash is ready

19-02-26 10:22:59.605  INFO 1652 --- [sh-api-executor] c.w..config.WebConfigurer          : Fetch toggles with status: UNAVAILABLE
10:22:59.605 [INFO ] [no_tenant ] c.w.s.config.WebConfigurer     - Fetch toggles with status: UNAVAILABLE
2019-02-26 10:24:05.733  INFO 1652 --- [sh-api-executor] c.w..config.WebConfigurer          : Fetch toggles with status: UNAVAILABLE
10:24:05.733 [INFO ] [no_tenant ] c.w.s.config.WebConfigurer     - Fetch toggles with status: UNAVAILABLE
2019-02-26 10:24:59.617  INFO 1652 --- [sh-api-executor] c.w..config.WebConfigurer          : Fetch toggles with status: UNAVAILABLE
10:24:59.617 [INFO ] [no_tenant ] c.w.s.config.WebConfigurer     - Fetch toggles with status: UNAVAILABLE
2019-02-26 10:26:00.718  INFO 1652 --- [sh-api-executor] c.w.submgn.config.WebConfigurer          : Fetch toggles with status: UNAVAILABLE
10:26:00.718 [INFO ] [no_tenant ] c.w.s.config.WebConfigurer     - Fetch toggles with status: UNAVAILABLE
2019-02-26 10:27:05.745  INFO 1652 --- [sh-api-executor] c.w.submgn.config.WebConfigurer          : Fetch toggles with status: UNAVAILABLE
10:27:05.745 [INFO ] [no_tenant ] c.w.s.config.WebConfigurer     - Fetch toggles with status: UNAVAILABLE
2019-02-26 10:27:59.881  INFO 1652 --- [sh-api-executor] c.w.submgn.config.WebConfigurer          : Fetch toggles with status: UNAVAILABLE
10:27:59.881 [INFO ] [no_tenant ] c.w.s.config.WebConfigurer     - Fetch toggles with status: UNAVAILABLE
2019-02-26 10:28:59.702  INFO 1652 --- [sh-api-executor] c.w..config.WebConfigurer          : Fetch toggles with status: UNAVAILABLE
10:28:59.702 [INFO ] [no_tenant ] c.w.s.config.WebConfigurer     - Fetch toggles with status: UNAVAILABLE
2019-02-26 10:29:59.706  INFO 1652 --- [sh-api-executor] c.w..config.WebConfigurer          : Fetch toggles with status: UNAVAILABLE
10:29:59.706 [INFO ] [no_tenant ] c.w.s.config.WebConfigurer     - Fetch toggles with status: UNAVAILABLE

status code 400 is coming later on

**Comment by ivarconr** [comment]
This is super wired! 

Can you also override the `onError` method on the subscriber and log out the full error message. 

Could you inspect the logs of unleash-server also?

400 response typically implies that the server is not happy with the request. 

I know multiple companies using the java client in production without issues (even my company, across 50+ java apps). I hope we can sort this out!

**Comment by vkatoch2000** [comment]
The problem is why it is working first time while taking backup , starts giving issues later

**Comment by vkatoch2000** [comment]
when accessing my instance over AWS load balancer I would always get: HTTP/1.1 400 BAD_REQUEST. 
Here are some findings given by someone i think this could be issue : 
 an empty header (no name and no value) because I had an empty row in HTTP Header Manager in jMeter. So, I persume, AWS ELB does some headers checking, and returns HTTP 400, even tough I wasn't having any problems with going with the same request to my instances directly. I don't know if this will help you but you should double-check your headers for some stupid mistake like this one :

**Comment by ivarconr** [comment]
This surprises me a lot. The initial request does indeed have an empty header, the `If-None-Match` header is bootstrapped with an empty string. 

This has been fixed in https://github.com/Unleash/unleash-client-java/commit/3ea27de72e7dda372de40a3a678600bebe315efc and released as `3.2.3`. I really hope this solves your issue.

Thanks for reporting, debugging help and your patience.  :+1: :tada: :1st_place_medal:

**Comment by vkatoch2000** [comment]
this etag coming null , throws  null pointer exception , can we put that check as well

**Comment by vkatoch2000** [comment]
it works , we can close this, t hanks for fixing this issue so fast......

**Comment by ivarconr** [comment]
...should probably add a `null` check also before closing.

**Comment by ivarconr** [comment]
adressed in #72
