### ISSUE TITLE
ClientRegistration Event - Suggestions

### ISSUE THREAD

**Issue by Green-Apple** [Unleash/unleash-client-java#86]
Small change suggestion. 
You may want to change getInterval() to getSendMetricInterval() as this could easily be confused with the fetchTogglesInterval value from the UnleashConfig if the source code isn't examined.

Also, I noticed that the ClientRegistration is pulling a several values from the UnleashConfig.  Would it make more sense to instead just store the entire UnleashConfig as an event variable instead of the few selected fields? That way, someone implementing the clientRegistered() method of the UnleashSubscriber can pick/choose which fields are relevant for them to log.

**Comment by ivarconr** [comment]
I agree with your suggestions. Will look in to it soon, when I have some time for it. 

Feel free to contribute a PR for it, but be careful about breaking changes. (E.g. we probably should deprecate "gerInterval' when adding the new method).

**Comment by chriswk** [comment]
After trying to write a PR and thinking about this a bit more, I think this is a wontfix.

UnleashConfig has a scheduled executor and a reference to a subscriber that doesn't lend itself easily to serialization. As such it doesn't make sense to include the entire config object in the event.

If there are specific fields from the config you're missing, feel free to submit a PR adding those fields to the event you need it in. But as of now, we won't include the entire config in the event.

**Comment by chriswk** [comment]
With regards to interval vs sendMetricsInterval, we do agree that the name may be confusing. However, the client specification requires the field to be serialized as interval for now. We might revisit that for a later major release.
