### ISSUE TITLE
Proxy support that recognizes -Dhttp.proxy* settings

### ISSUE THREAD

**Issue by dennis-menge** [Unleash/unleash-client-java#90]
Hello everyone,

I am currently playing around with the unleash java client. It works really well, I only struggled a little bit with the proxy configuration. 

As you use HttpUrlConnection as http client, basic auth proxy settings are not recognized, i.e.:
- http.proxyUser
- http.proxyPassword

Therefore, it is necessary to implement a custom java.net.Authenticator. What do you think of providing such an implementation within the library itself? If so, I would try to create a PR for that.

Thank you in advance!

**Comment by ivarconr** [comment]
Hi there,

I'm not that familiar with proxy user/password things in java. What is required for HttpUrlConnection to use proxy configuration that is set up at the Java level?

**Comment by ivarconr** [comment]
Seems like this is it: https://www.admfactory.com/http-urlconnection-with-proxy-in-java/

As long as we can keep it to built-in libraries in java I see no issues with adding proxy-support. I would be happy to assist you in adding this @dennis-menge

**Comment by dennis-menge** [comment]
Awesome, I will submit something today or tomorrow.

It is basically "just" implementing an Authenticator that recognizes those "standard" JVM Settings.

**Comment by dennis-menge** [comment]
PR opened #91
