### ISSUE TITLE
chore: Add code-formatting rules

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-java#92]
Pick a widely adopted standard supported by major java-IDEs (intellij, eclipse, visual studio) and define the rules for this project. This makes it easier for outsiders to contribute!

Options:
- https://google.github.io/styleguide/javaguide.html
- https://checkstyle.sourceforge.io/

Others we should consider?

**Comment by chriswk** [comment]
Solved in 3fe43a294
